IMPORTING DATA

```{r}

library(cluster)
library(factoextra)
library(NbClust)

data = read.csv('./data/Financial_Data.csv')
data <- data[2:(length(data)-4)]
```



PCA

```{r}
pca_res <- prcomp(data, scale = FALSE)
#get_eig(pca_res)
fviz_eig(pca_res,ncp=30)
plot(get_eig(pca_res)$cumulative.variance.percent, type='b', axes=F, xlab='n', ylab='cumulative PVE', ylim=c(0,100))
abline(h=100, col='blue')
abline(h=80, lty=2, col='blue') # thesholding
box()
axis(2, at=0:100,labels=0:100)
axis(1,at=1:ncol(data),labels=1:ncol(data),las=2)
fviz_pca_var(pca_res,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),repel = TRUE)    # Avoid text overlapping
```






CLUSTERING

```{r}
restricted_data = pca_res$x[1:100,1:65]
restricted_data = restricted_data[-c(match(c(1,3),km_res$cluster)), ]
distances = dist(restricted_data, method='euclidean')
```



```{r}

# Hierarchical clustering


#Compute hierarchical clustering
hc_centroid <- hclust(distances, method='centroid') # for centroid linkage
hc_complete <- hclust(distances, method='complete')

#Plot black tree
fviz_dend(hc_centroid, as.ggplot = TRUE, show_labels = FALSE, main='Euclidean-Centroid')

#identifying 2 groups by #clusters (=2)
cluster_k <- cutree(hc_complete, k = 2)

#identifying groups below height 3.8
cluster_h <- cutree(hc_complete, h = 3.8) 

#Plot the tree with cluster colors
fviz_dend(hc_complete, k = 2, k_colors = "jco", as.ggplot = TRUE, show_labels = FALSE, main='Euclidean-Complete')

#Plot clusterization with defined height
fviz_dend(hc_complete, h = 3.8, k_colors = "jco", as.ggplot = TRUE, show_labels = FALSE, main='Euclidean-Complete')
```

```{r}
#######################################
# K-MEANS
res <- kmeans(restricted_data, 3)   # K = 3 here

#K-MEANS with cool plot associated (on 2D plane of the first principal components)
km_res <- eclust(restricted_data, "kmeans", k = 3, hc_metric = "euclidean")

```
NB: ogni volta che chiami un clusterizzatore, ti ritorna un dizionario, come km_res.
Puoi accedere ai suoi elementi con km_res$sottoelemento



```{r}
#Silhouettes

fviz_nbclust(restricted_data, kmeans, method = "silhouette")+
  labs(subtitle = "Silhouette method")
```

```{r}
sil <- silhouette(x=km_res$cluster, dist = distances)
```

```{r}
fviz_silhouette(sil)
```
